import type { PrismaClient } from '@prisma/client';

import { env } from '../config/env.js';
import type { AnalysisResult, ChannelSnapshot } from '../types/analysis.js';
import { classifyCommentIntent } from './comment-intent.js';

type PersistArgs = {
  prisma: PrismaClient;
  snapshot: ChannelSnapshot;
  result: AnalysisResult;
  channelUrl: string;
  maxVideos: number;
};

export async function persistAnalysis({
  prisma,
  snapshot,
  result,
  channelUrl,
  maxVideos
}: PersistArgs): Promise<void> {
  const channel = await prisma.channel.upsert({
    where: { url: channelUrl },
    update: {
      title: result.channel.title,
      nicheLabel: result.channel.niche,
      youtubeChannelId: snapshot.channelId
    },
    create: {
      url: channelUrl,
      title: result.channel.title,
      nicheLabel: result.channel.niche,
      youtubeChannelId: snapshot.channelId
    }
  });

  await prisma.video.deleteMany({
    where: {
      channelId: channel.id
    }
  });

  for (const video of snapshot.videos) {
    const savedVideo = await prisma.video.create({
      data: {
        channelId: channel.id,
        youtubeVideoId: video.videoId,
        title: video.title,
        description: video.description,
        publishedAt: new Date(video.publishedAt)
      }
    });

    await prisma.videoMetric.create({
      data: {
        videoId: savedVideo.id,
        viewCount: video.views,
        likeCount: video.likes,
        commentCount: video.commentsCount,
        velocityScore:
          video.views /
          Math.max(
            1,
            Math.floor(
              (Date.now() - new Date(video.publishedAt).getTime()) / (1000 * 60 * 60 * 24)
            )
          )
      }
    });

    if (video.transcriptSnippet) {
      await prisma.transcript.create({
        data: {
          videoId: savedVideo.id,
          source: env.YOUTUBE_API_KEY ? 'youtube_api_context' : 'fallback_generated',
          language: 'en',
          transcriptText: video.transcriptSnippet,
          isAutoGenerated: true
        }
      });
    }

    for (const comment of video.sampleComments) {
      await prisma.comment.create({
        data: {
          videoId: savedVideo.id,
          text: comment,
          intentLabel: classifyCommentIntent(comment)
        }
      });
    }
  }

  await prisma.analysis.create({
    data: {
      channelId: channel.id,
      status: 'completed',
      inputConfig: {
        channelUrl,
        maxVideos,
        mode: env.YOUTUBE_API_KEY ? 'youtube_api' : 'fallback'
      },
      resultJson: JSON.parse(JSON.stringify(result)),
      completedAt: new Date()
    }
  });
}
