import type { PrismaClient } from '@prisma/client';

import type { AnalysisResult, ChannelSnapshot } from '../types/analysis.js';
import { computeVelocity } from './analysis-engine.js';
import { classifyCommentIntent } from './comment-intent.js';

type PersistArgs = {
  prisma: PrismaClient;
  snapshot: ChannelSnapshot;
  result: AnalysisResult;
  channelUrl: string;
  maxVideos: number;
};

/**
 * Persist a completed analysis atomically. The previous video set is replaced by
 * the new snapshot inside one transaction so a mid-write failure can never leave
 * a channel half-deleted, and readers never observe a partial state.
 */
export async function persistAnalysis({
  prisma,
  snapshot,
  result,
  channelUrl,
  maxVideos
}: PersistArgs): Promise<void> {
  await prisma.$transaction(async (tx) => {
    const channel = await tx.channel.upsert({
      where: { url: channelUrl },
      update: {
        title: result.channel.title,
        nicheLabel: result.channel.niche,
        youtubeChannelId: snapshot.channelId,
        dataSource: snapshot.dataSource
      },
      create: {
        url: channelUrl,
        title: result.channel.title,
        nicheLabel: result.channel.niche,
        youtubeChannelId: snapshot.channelId,
        dataSource: snapshot.dataSource
      }
    });

    await tx.video.deleteMany({
      where: {
        channelId: channel.id
      }
    });

    for (const video of snapshot.videos) {
      await tx.video.create({
        data: {
          channelId: channel.id,
          youtubeVideoId: video.videoId,
          title: video.title,
          description: video.description,
          publishedAt: new Date(video.publishedAt),
          metricSnapshots: {
            create: {
              viewCount: video.views,
              likeCount: video.likes,
              commentCount: video.commentsCount,
              velocityScore: computeVelocity(video)
            }
          },
          transcript: video.transcriptSnippet
            ? {
                create: {
                  source:
                    snapshot.dataSource === 'youtube' ? 'youtube_api_context' : 'demo_generated',
                  language: 'en',
                  transcriptText: video.transcriptSnippet,
                  isAutoGenerated: true
                }
              }
            : undefined,
          comments: {
            createMany: {
              data: video.sampleComments.map((comment) => ({
                youtubeCommentId: comment.commentId,
                text: comment.text,
                intentLabel: classifyCommentIntent(comment.text),
                likeCount: comment.likeCount,
                publishedAt: comment.publishedAt ? new Date(comment.publishedAt) : undefined
              }))
            }
          }
        }
      });
    }

    await tx.analysis.create({
      data: {
        channelId: channel.id,
        status: 'completed',
        dataSource: snapshot.dataSource,
        inputConfig: {
          channelUrl,
          maxVideos,
          mode: snapshot.dataSource
        },
        resultJson: JSON.parse(JSON.stringify(result)),
        completedAt: new Date()
      }
    });
  });
}
